spring:
  profiles: default
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:mem:flight-app;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      trace: false
      web-allow-others: false